### list
GET http://localhost:9129/list?app=app1&env=dev&ns=public

### update
POST http://localhost:9129/update?app=app1&env=dev&ns=public
Content-Type: application/json


{
  "hb.a": "dev200",
  "hb.c": "cc200",
  "hb.d": "dd200"
}

