server:
    port: 9129

spring:
    application:
        name: hbconfig-server
    datasource:
#        driver-class-name: org.h2.Driver
#        url: jdbc:h2:mem:h2db
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/hbconfig?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password:
    sql:
      init:
          schema-locations: classpath:db.sql
          mode: always
    h2:
      console:
          enabled: true
          path: /h2
          settings:
              web-allow-others: true
